# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0002_auto_20161207_2255'),
        ('GroupsApp', '0002_auto_20161208_0059'),
    ]

    operations = [
    ]
