# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
