# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0008_auto_20161208_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
    ]
