# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0015_feature'),
        ('GroupsApp', '0010_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='features',
            field=models.ManyToManyField(default=None, to='ProjectsApp.Feature'),
        ),
    ]
