# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0011_group_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
