# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0012_comment_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_type',
            field=models.CharField(default='Visitor', max_length=100),
        ),
    ]
