# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0001_initial'),
        ('ProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
    ]
