# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yrs_of_exp',
            field=models.IntegerField(default=0),
        ),
    ]
