# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0007_project_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='interests',
            new_name='specialty',
        ),
    ]
