# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0008_auto_20161208_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='project',
            name='yrs_of_exp',
        ),
        migrations.AddField(
            model_name='project',
            name='back_end_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='c_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='front_end_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='full_stack_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='java_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='mobile_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='no_lang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='no_specialty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='python_lang',
            field=models.BooleanField(default=False),
        ),
    ]
