# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0013_auto_20161208_0611'),
        ('ProjectsApp', '0013_auto_20161208_0520'),
    ]

    operations = [
    ]
