# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0002_comment_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
