# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_auto_20161207_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
