# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_auto_20161208_0059'),
        ('AuthenticationApp', '0008_auto_20161207_2255'),
    ]

    operations = [
    ]
