# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0009_merge_20161208_0450'),
        ('AuthenticationApp', '0009_merge_20161208_0520'),
    ]

    operations = [
    ]
