# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_merge_20161208_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='back_end_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='c_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='front_end_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='full_stack_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='java_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_spec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='no_lang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='no_spec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='python_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='yrs_of_exp',
            field=models.IntegerField(default=0),
        ),
    ]
