# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 10:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0011_auto_20161208_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='about',
            field=tinymce.models.HTMLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='about',
            field=tinymce.models.HTMLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=tinymce.models.HTMLField(default=None),
            preserve_default=False,
        ),
    ]
