# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0012_auto_20161208_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='photo',
            field=models.ImageField(default=0, upload_to='static/userimages'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=0, upload_to='static/userimages'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default=0, upload_to='static/userimages'),
        ),
    ]
